<?php

namespace AppBundle\Repository;

/**
 * PresenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresenceRepository extends \Doctrine\ORM\EntityRepository {
    
    public function findAllUsersInWork() {
        
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT p, u '
              . 'FROM AppBundle:Presence p '
              . 'JOIN p.user u '
              . 'WHERE p.timeOut IS NULL AND p.type LIKE \'work\' '      
              . 'ORDER BY u.name'
            );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }        
    }
    
    public function findWorkload() {
        
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT p, u, COUNT(p.user) AS sessions, SEC_TO_TIME(SUM(TIME_TO_SEC(p.timeOut) - TIME_TO_SEC(p.timeIn))) AS timeDiff, '
              . 'SUM(TIME_TO_SEC(p.timeOut) - TIME_TO_SEC(p.timeIn)) AS timeDiffSec '      
              . 'FROM AppBundle:Presence p '
              . 'JOIN p.user u '
              . 'WHERE p.type = \'work\' '      
              . 'GROUP BY p.user '      
              . 'ORDER BY u.name'
            );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }        
    }
    
}
