<?php

namespace AppBundle\Repository;

/**
 * PresenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresenceRepository extends \Doctrine\ORM\EntityRepository {
    
    public function findAllUsers() {
        
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT p, u '
              . 'FROM AppBundle:Presence p '
              . 'JOIN p.user u '
              . 'GROUP BY p.token '
              . 'HAVING COUNT(p.token) = 1 '
              . 'ORDER BY u.name'
            );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }        
    }
    
}
